from algorithms.MatrixTimesVector import scalar_multiply
from algorithms.ScalarMultiplicationofaMatrix import matrix_dot_vector
from algorithms.CalculateCovarianceMatrix import calculate_covariance_matrix
from algorithms.LinearRegressionUsingNormalEquation import linear_regression_normal_equation

